// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeZ6Ypmkai4oSBuyp1mJuRKEwKow089ZY',
    appId: '1:270232624268:web:8039e5bbf2d82c3d4d2fa9',
    messagingSenderId: '270232624268',
    projectId: 'finaltodoapp-a0de7',
    authDomain: 'finaltodoapp-a0de7.firebaseapp.com',
    storageBucket: 'finaltodoapp-a0de7.appspot.com',
    measurementId: 'G-BFH547F15V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB91sslB0DOgbVMVXHHQBfkuP-Rtpls6DQ',
    appId: '1:270232624268:android:e0ba6f666fa43cb94d2fa9',
    messagingSenderId: '270232624268',
    projectId: 'finaltodoapp-a0de7',
    storageBucket: 'finaltodoapp-a0de7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOdvlI5vOjVIqBkC7C_0eva6Ez8K-eVaQ',
    appId: '1:270232624268:ios:d419d1efc872d1654d2fa9',
    messagingSenderId: '270232624268',
    projectId: 'finaltodoapp-a0de7',
    storageBucket: 'finaltodoapp-a0de7.appspot.com',
    iosBundleId: 'com.example.finalToDoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOdvlI5vOjVIqBkC7C_0eva6Ez8K-eVaQ',
    appId: '1:270232624268:ios:d419d1efc872d1654d2fa9',
    messagingSenderId: '270232624268',
    projectId: 'finaltodoapp-a0de7',
    storageBucket: 'finaltodoapp-a0de7.appspot.com',
    iosBundleId: 'com.example.finalToDoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBeZ6Ypmkai4oSBuyp1mJuRKEwKow089ZY',
    appId: '1:270232624268:web:0f088d6c334fdbc14d2fa9',
    messagingSenderId: '270232624268',
    projectId: 'finaltodoapp-a0de7',
    authDomain: 'finaltodoapp-a0de7.firebaseapp.com',
    storageBucket: 'finaltodoapp-a0de7.appspot.com',
    measurementId: 'G-0CFZSXE1MG',
  );
}
